### ISSUE TITLE
docker-compose up 時などに GraphQLのクライアントとして利用しているコンテナが落ちる

### ISSUE THREAD

**Issue by k0kishima** [k0kishima/boatrace_docker#1]
## 原因

`docker-compose  up` 時に以下のような事象が発生

```shell
forecaster_1                | Exiting
forecaster_1                | /usr/local/bundle/gems/graphql-1.12.7/lib/graphql/schema/loader.rb:17:in `fetch': key not found: "data" (KeyError)
forecaster_1                | 	from /usr/local/bundle/gems/graphql-1.12.7/lib/graphql/schema/loader.rb:17:in `load'
forecaster_1                | 	from /usr/local/bundle/gems/graphql-client-0.16.0/lib/graphql/client.rb:52:in `load_schema'
forecaster_1                | 	from /usr/local/bundle/gems/graphql-client-0.16.0/lib/graphql/client.rb:61:in `load_schema'
forecaster_1                | 	from /app/config/initializers/graphql_client.rb:16:in `<module:SWAPI>'
forecaster_1                | 	from /app/config/initializers/graphql_client.rb:5:in `<main>'
forecaster_1                | 	from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
forecaster_1                | 	from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
forecaster_1                | 	from /usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:318:in `block in load'
forecaster_1                | 	from /usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:291:in `load_dependency'
forecaster_1                | 	from /usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:318:in `load'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/engine.rb:666:in `block in load_config_initializer'
forecaster_1                | 	from /usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/notifications.rb:182:in `instrument'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/engine.rb:665:in `load_config_initializer'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/engine.rb:625:in `block (2 levels) in <class:Engine>'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/engine.rb:624:in `each'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/engine.rb:624:in `block in <class:Engine>'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/initializable.rb:32:in `instance_exec'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/initializable.rb:32:in `run'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/initializable.rb:61:in `block in run_initializers'
forecaster_1                | 	from /usr/local/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
forecaster_1                | 	from /usr/local/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
forecaster_1                | 	from /usr/local/lib/ruby/3.0.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
forecaster_1                | 	from /usr/local/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
forecaster_1                | 	from /usr/local/lib/ruby/3.0.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/initializable.rb:50:in `each'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/initializable.rb:50:in `tsort_each_child'
forecaster_1                | 	from /usr/local/lib/ruby/3.0.0/tsort.rb:415:in `call'
forecaster_1                | 	from /usr/local/lib/ruby/3.0.0/tsort.rb:415:in `each_strongly_connected_component_from'
forecaster_1                | 	from /usr/local/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
forecaster_1                | 	from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each'
forecaster_1                | 	from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `call'
forecaster_1                | 	from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
forecaster_1                | 	from /usr/local/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
forecaster_1                | 	from /usr/local/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/initializable.rb:60:in `run_initializers'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/application.rb:363:in `initialize!'
forecaster_1                | 	from /app/config/environment.rb:5:in `<main>'
forecaster_1                | 	from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
forecaster_1                | 	from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
forecaster_1                | 	from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
forecaster_1                | 	from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
forecaster_1                | 	from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
forecaster_1                | 	from /usr/local/bundle/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
forecaster_1                | 	from /usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `block in require'
forecaster_1                | 	from /usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:291:in `load_dependency'
forecaster_1                | 	from /usr/local/bundle/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `require'
forecaster_1                | 	from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
forecaster_1                | 	from config.ru:3:in `block in <main>'
forecaster_1                | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
forecaster_1                | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
forecaster_1                | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
forecaster_1                | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
forecaster_1                | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
forecaster_1                | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
forecaster_1                | 	from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/commands/server/server_command.rb:37:in `start'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/commands/server/server_command.rb:147:in `block in perform'
forecaster_1                | 	from <internal:kernel>:90:in `tap'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/commands/server/server_command.rb:138:in `perform'
forecaster_1                | 	from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
forecaster_1                | 	from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
forecaster_1                | 	from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/command/base.rb:69:in `perform'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/command.rb:46:in `invoke'
forecaster_1                | 	from /usr/local/bundle/gems/railties-6.0.3.6/lib/rails/commands.rb:18:in `<main>'
forecaster_1                | 	from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
forecaster_1                | 	from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
forecaster_1                | 	from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
forecaster_1                | 	from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
forecaster_1                | 	from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
forecaster_1                | 	from /app/bin/rails:9:in `<top (required)>'
forecaster_1                | 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
forecaster_1                | 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
forecaster_1                | 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
forecaster_1                | 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
forecaster_1                | 	from /usr/local/bundle/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
forecaster_1                | 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
forecaster_1                | 	from /usr/local/bundle/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
forecaster_1                | 	from /app/bin/spring:15:in `require'
forecaster_1                | 	from /app/bin/spring:15:in `<top (required)>'
forecaster_1                | 	from bin/rails:3:in `load'
forecaster_1                | 	from bin/rails:3:in `<main>'
boatrace_docker_forecaster_1 exited with code 1
```

GraphQLの introspection request が失敗することによって発生する例外で落ちている

## 修正後に期待する振る舞い

* 当該エラーが発生しなくなること
* 結果としてコンテナの実行が終了されずに起動し続けられるようになること

**Comment by k0kishima** [comment]
エラー自体はクライアントの監査クエリが原因だが、そもそもGraphQLサーバーがDB未設定原因でエラーになってるので起動時にmigration実行するようにしてDB未設定にならないようにした。
